services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api-1:
    build: .
    ports:
      - "8888:8888"
    environment:
      - REDIS_HOST=redis
      - HOSTNAME=api-1
    depends_on:
      - redis

  api-2:
    build: .
    ports:
      - "8889:8888"
    environment:
      - REDIS_HOST=redis
      - HOSTNAME=api-2
    depends_on:
      - redis

  api-3:
    build: .
    ports:
      - "8890:8888"
    environment:
      - REDIS_HOST=redis
      - HOSTNAME=api-3
    depends_on:
      - redis
